### ISSUE TITLE
Bug: Doesn't recognize Brave browser in my Linux

### ISSUE THREAD

**Issue by tomByrer** [diffusionstudio/core#1]
I got the warning
```
Diffusion Studio works with Google Chrome 113+
To use Diffusion Studio please switch to a modern desktop version of Chrome.
```
I'm guessing all the Chrome-ish browsers (Edge, Breve, Vivaldi, Opera,  [ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium), [Thorium](https://thorium.rocks/), etc don't have access?

Might be better to check for 2-3 of the newest features you need before blocking IMHO.

**Comment by k9p5** [comment]
This isn't necessarily related to the core library, Edge works fine and I have just verified that it's working on Breve, thanks for the pull.

**Comment by tomByrer** [comment]
Sorry, can you re-open please; still doesn't work in Brave in my Linux Mint desktop.  FF does though
![image](https://github.com/user-attachments/assets/d9f0bdf4-a99f-4fd6-b2bf-3112afd9cced)

**Comment by k9p5** [comment]
The browser detection of the app (which is a separate project) is unrelated to this library, you can just install the library and try for yourself if its working on brave. At least it was for me on MacOs
