### ISSUE TITLE
Clip id’s able to set

### ISSUE THREAD

**Issue by girayk** [diffusionstudio/core#21]
Some projects we re recalling clips from db, etc. Can we make id’s re able to set, it’s will save time to chase them 😂

**Comment by k9p5** [comment]
I'm not quite sure what you're referring to, could you elaborate?

**Comment by girayk** [comment]
https://github.com/diffusionstudio/core/blob/9a501fee9aa442c749bfecbc215c34b9b2c75d5f/src/mixins/event.ts#L27

The ids on clips are random and not over writable.

**Comment by k9p5** [comment]
Is the `name` property not sufficient? It's like an ID but user defined

**Comment by voladelta** [comment]
i can't set name, i'd love to set `id` as well
<img width="1244" alt="image" src="https://github.com/user-attachments/assets/b25efeef-56b9-46f8-8c8d-7f69f64304a5">
<img width="650" alt="image" src="https://github.com/user-attachments/assets/fe9bc96a-1519-44f0-84d4-760ccbc1fa05">

**Comment by girayk** [comment]
other hand, name is could something visible and id is something private.
for example when i add 2.mp4 on my project, i would like to show name on timeline etc wiith original name and i need to use id for able to identify them. name is could be same for anything but id must have uniqiue.
second name is depraceted on pixi, we need use label instead of Name.

**Comment by k9p5** [comment]
That's true, `clip.name` is meant to be displayed on the timeline. I have now made the id writable: https://github.com/diffusionstudio/core/pull/22/commits/416075bba528677a22cf0a2970beecae0b9a1524 let me know if that works for you

**Comment by k9p5** [comment]
That's true, `clip.name` is meant to be displayed on the timeline. I have now made the id writable: https://github.com/diffusionstudio/core/pull/22/commits/416075bba528677a22cf0a2970beecae0b9a1524 let me know if that works for you
