### ISSUE TITLE
Cant not export with video with mp3 or wav

### ISSUE THREAD

**Issue by voladelta** [diffusionstudio/core#36]
I can export video just fine without audio. When come to audio like mp3 or wav in the composition, i can't export it.

I try with default or sampleRate: 44100. 

The error is weird as well:
`SecurityError: Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.`

Without audio, showSaveFilePicker shows.

An audio sample is: https://zokjuqrjbkfkymnqwxui.supabase.co/storage/v1/object/public/media/4e728193-25d3-4bf6-b96a-90db1cbc880d.mp3

**Comment by voladelta** [comment]
Btw, i can play the composition in the player.

**Comment by girayk** [comment]
You have to put it inside to onClick function

**Comment by voladelta** [comment]
> You have to put it inside to onClick function

yeah, i did. click to trigger export.
If i remove audio, i can export video with captions 
(and download the audio separately for capcut) to sync.

but it isnt the good ux for user.

**Comment by voladelta** [comment]
I solved the issue by uploading file to supabase presigned url. The is my prefered method as well.
